-- Données de démarrage pour le développement local (supabase db reset).
-- À adapter/compléter directement depuis le dashboard Supabase en production.

insert into public.forfaits (nom, prix, description, badge, ordre_affichage) values
  ('Vidange autobloquant', 169.00,
   'Vidange du différentiel autobloquant / Haldex : huile préconisée constructeur et contrôle d''étanchéité.',
   null, 1),
  ('Liquide de frein + purge', 189.00,
   'Liquide de frein haute température et purge complète du circuit de freinage. Idéal usage sportif.',
   null, 2),
  ('Vidange boîte + filtre', 329.00,
   'Huile d''origine adaptée à votre boîte (DSG, S tronic, automatique...), remplacement du filtre à huile et adaptation à la valise. Préserve la douceur et la fiabilité des passages.',
   'Le plus demandé', 3),
  ('Mise à jour cartographie', 350.00,
   'Évolution de votre cartographie existante : nouvelle version, adaptation aux modifications du véhicule, validation au banc.',
   null, 4),
  ('Préparation & reprogrammation', null,
   'Stage 1 à 4, conversion E85, moteur forgé : chaque projet est unique et chiffré précisément après échange sur vos objectifs.',
   null, 5);

-- logo_url is only set for brands with a clean flat, freely-licensed vector
-- logo on hand (simple-icons, CC0, or a public-domain SVG from Wikimedia
-- Commons for trademarked-but-uncopyrightable marks). The rest fall back to
-- the initials badge in MarquesGrid.
insert into public.marques (nom, logo_url) values
  ('Audi', '/brand/audi.svg'),
  ('BMW', '/brand/bmw.svg'),
  ('Mercedes-Benz', '/brand/mercedes-benz.svg'),
  ('Volkswagen', '/brand/volkswagen.svg'),
  ('SEAT', '/brand/seat.svg'),
  ('Škoda', '/brand/skoda.svg'),
  ('Porsche', '/brand/porsche.svg'),
  ('Volvo', '/brand/volvo.svg'),
  ('Citroën', '/brand/citroen.svg'),
  ('Ford', '/brand/ford.svg'),
  ('Opel', '/brand/opel.svg'),
  ('Fiat', '/brand/fiat.svg'),
  ('Alfa Romeo', '/brand/alfa-romeo.svg'),
  ('Mini', '/brand/mini.svg'),
  ('Nissan', '/brand/nissan.svg'),
  ('Toyota', '/brand/toyota.svg'),
  ('Honda', '/brand/honda.svg'),
  ('Mazda', '/brand/mazda.svg'),
  ('Hyundai', '/brand/hyundai.svg'),
  ('Kia', '/brand/kia.svg'),
  ('Jaguar', '/brand/jaguar.svg'),
  ('Land Rover', '/brand/land-rover.svg'),
  ('Cupra', '/brand/cupra.svg'),
  ('Abarth', '/brand/abarth.svg'),
  ('DS Automobiles', '/brand/ds-automobiles.svg'),
  ('Dacia', '/brand/dacia.svg'),
  ('Suzuki', '/brand/suzuki.svg'),
  ('Subaru', '/brand/subaru.svg'),
  ('Yamaha', '/brand/yamaha.svg'),
  ('Alpine', '/brand/alpine.svg'),
  ('Aston Martin', '/brand/aston-martin.svg'),
  ('Bentley', '/brand/bentley.svg'),
  ('Bugatti', '/brand/bugatti.svg'),
  ('Ferrari', '/brand/ferrari.svg'),
  ('Genesis', '/brand/genesis.svg'),
  ('Jeep', '/brand/jeep.svg'),
  ('KTM', '/brand/ktm.svg'),
  ('Lamborghini', '/brand/lamborghini.svg'),
  ('Lancia', '/brand/lancia.svg'),
  ('Lexus', '/brand/lexus.svg'),
  ('Lotus', '/brand/lotus.svg'),
  ('Maserati', '/brand/maserati.svg'),
  ('McLaren', '/brand/mclaren.svg'),
  ('MG', '/brand/mg.svg'),
  ('Mitsubishi', '/brand/mitsubishi.svg'),
  ('Polestar', '/brand/polestar.svg'),
  ('Rolls-Royce', '/brand/rolls-royce.svg'),
  ('Smart', '/brand/smart.svg'),
  ('Tesla', '/brand/tesla.svg')
on conflict (nom) do update set logo_url = excluded.logo_url;

-- Constructions réelles issues du compte Instagram @amkdeveloppement01.
-- ch_final / couple_nm reprennent le meilleur résultat annoncé (carburant précisé
-- quand la publication distingue plusieurs cartographies). couple_nm_origine et
-- cent_deux_cent (chrono 100->200 km/h) ne sont renseignés que lorsque la
-- publication d'origine le donnait explicitement — jamais estimés. Aucune
-- publication ne donne de vrai temps 0-100, donc zero_cent reste vide partout.
-- delta_ch / delta_couple_nm sont des colonnes générées, pas besoin de les insérer.
insert into public.realisations
  (marque, modele, stage, ch_origine, ch_final, couple_nm, couple_nm_origine, cent_deux_cent, carburant, image_url, description, ordre_affichage) values
  ('Audi', 'RS3', 4, 400, 1025, 1080, null, 3.30, 'E85',
   '/realisations/audi-rs3-stage4-1025ch.jpg',
   'Kit turbo JDY complet, gestion électronique sur mesure.', 1),
  ('Audi', 'RS6 C8 Mansory', 3, 605, 916, 1219, 800, 5.39, 'SP98',
   '/realisations/audi-rs6-c8-mansory-stage3.jpg',
   'Turbo TTE1020, intercooler et admission Eventuri, pompe à carburant renforcée.', 2),
  ('Audi', 'TT-RS 8S', 4, 400, 843, 936, 480, null, 'E85',
   '/realisations/audi-tt-rs-8s-stage4.jpg',
   'Bloc forgé, turbo TTE777, admission APR carbone, 4 cartographies dont une piste.', 3),
  ('Audi', 'RS3 8V2', 3, 400, 759, 812, null, null, 'E85',
   '/realisations/audi-rs3-8v2-olive-stage3.jpg',
   'Bielles et pistons forgés, turbo TTE700, décata, admission, échangeur.', 4),
  ('Audi', 'RS3', 3, 400, 716, 885, null, 5.30, null,
   '/realisations/audi-rs3-violet-stage3.jpg',
   'Moteur forgé, embrayage renforcé, collecteur d''admission gros volume, échangeur Wagner.', 5),
  ('Audi', 'RS3 8V2', 2, 400, 610, 723, 480, null, 'E85',
   '/realisations/audi-rs3-8v2-noir-stage2.jpg',
   'Échangeur, admission et inlet CTS, bougies NGK, décata.', 7),
  ('BMW', 'M2 Compétition', 2, 410, 607, 851, 550, null, 'E85',
   '/realisations/bmw-m2-competition-stage2.jpg',
   'Cartographie multimap, suppression FAP, renfort de poulie.', 8),
  ('Audi', 'RS3 8V2', 2, 400, 561, 674, null, null, 'E85',
   '/realisations/audi-rs3-8v2-vert-stage2.jpg',
   'Downpipe Milltek, cartographie multimap moteur & boîte.', 9),
  ('Audi', 'TT RS', 2, 388, 555, 740, 507, null, 'E85',
   '/realisations/audi-tt-rs-8s-stage2.jpg',
   'Décata/défap Milltek, échangeur Wagner, admission Eventuri.', 10),
  ('Volkswagen', 'Polo WRC', 3, 220, 527, 700, 320, 5.40, 'E85',
   '/realisations/vw-polo-wrc-stage3.jpg',
   'Bloc forgé, turbo hybride, boîte et embrayage renforcés, multimap full E85.', 11),
  ('Audi', 'RS3 8Y', 2, 404, 522, 643, 537, 7.97, null,
   '/realisations/audi-rs3-8y-rose-stage2.jpg',
   'Ligne complète décata/défap, admission Eventuri.', 12),
  ('Volkswagen', 'Golf 7R', 3, 340, 454, 539, null, null, 'SP95',
   '/realisations/vw-golf-7r-stage3.jpg',
   'Cartographie stage 3 moteur et boîte au SP95.', 13),
  ('Volkswagen', 'Polo (swap 1.8 TSI)', 3, 192, 443, 554, null, null, 'E85',
   '/realisations/vw-polo-swap-18tsi-stage3.jpg',
   'Swap 1.8 TSI 192, turbo TTH440, injecteurs 980cc, décata, embrayage renforcé, boîte modifiée.', 14),
  ('BMW', 'M2 Compétition', 1, 481, 546, 756, 704, null, 'SP98',
   '/realisations/bmw-m2-competition-stage1.jpg',
   'Amortisseurs KW, échangeur do88, ligne M-Perf et renfort de poulie déjà présents ; cartographie Stage 1 AMK.', 15),
  ('Volkswagen', 'Polo WRC', 4, 220, 819, 854, 350, null, 'E85',
   '/realisations/vw-polo-wrc-stage4.jpg',
   'Bloc moteur forgé bi-injection, autobloquant, aile avant large, pneus 235 R888R, suspension KW Compétition, échangeur frontal sur mesure, wastegate externe, admission, suralimentation par R2F, gestion 4 modes jusqu''à 819 ch.', 16),
  ('Yamaha', 'R7', 1, 47, 77, 71, 66, null, 'SP98',
   '/realisations/yamaha-r7-stage1.jpg',
   'Débridage mécanique et électronique, ligne complète SC Project, cartographie Stage 1 SP98.', 17);
